/** @type {import('tailwindcss').Config} */
module.exports = {
	content: [
		"./node_modules/flowbite/**/*.js",
		"*.{php,html}",
		"./src/**/*.{php,js,html}",
	],
	theme: {
		extend: {},
	},
	plugins: [
		require("daisyui"),
		require("@tailwindcss/typography"),
		require("@tailwindcss/forms"),
		require("flowbite/plugin")({
			charts: true,
		}),
	],
	daisyui: {
		themes: [
			"light",
			"dark",
			"cupcake",
			"bumblebee",
			"emerald",
			"corporate",
			"synthwave",
			"retro",
			"cyberpunk",
			"valentine",
			"halloween",
			"garden",
			"forest",
			"aqua",
			"lofi",
			"pastel",
			"fantasy",
			"wireframe",
			"black",
			"luxury",
			"dracula",
			"cmyk",
			"autumn",
			"business",
			"acid",
			"lemonade",
			"night",
			"coffee",
			"winter",
			"dim",
			"nord",
			"sunset",
		],
	},
};
